"""начальна миграция

Revision ID: f2318fd2b927
Revises:
Create Date: 2025-10-30 21:16:20.306767

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2318fd2b927"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backups")),
        sa.UniqueConstraint("name", name=op.f("uq_backups_name")),
    )
    op.create_index(op.f("ix_backups_id"), "backups", ["id"], unique=True)
    op.create_table(
        "processes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processes")),
        sa.UniqueConstraint("name", name=op.f("uq_processes_name")),
    )
    op.create_index(op.f("ix_processes_id"), "processes", ["id"], unique=True)
    op.create_table(
        "step_templates",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_step_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_step_templates_name")),
    )
    op.create_index(op.f("ix_step_templates_id"), "step_templates", ["id"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_table(
        "access_tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_access_tokens_user_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_access_tokens")),
    )
    op.create_index(
        op.f("ix_access_tokens_created_at"),
        "access_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "employees",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "worker", name="role_enum"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_employees_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("name", name=op.f("uq_employees_name")),
        sa.UniqueConstraint("user_id", name=op.f("uq_employees_user_id")),
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=True)
    op.create_table(
        "products",
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
            name=op.f("fk_products_process_id_processes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_products_serial_number")),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=True)
    op.create_table(
        "step_definitions",
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
            name=op.f("fk_step_definitions_process_id_processes"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["step_templates.id"],
            name=op.f("fk_step_definitions_template_id_step_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_step_definitions")),
    )
    op.create_index(
        op.f("ix_step_definitions_id"), "step_definitions", ["id"], unique=True
    )
    op.create_table(
        "daily_plans",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("planned_steps", sa.Integer(), nullable=False),
        sa.Column("actual_steps", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_daily_plans_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_plans")),
    )
    op.create_index(op.f("ix_daily_plans_id"), "daily_plans", ["id"], unique=True)
    op.create_table(
        "product_steps",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("step_definition_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "done", name="step_status_enum"),
            nullable=False,
        ),
        sa.Column("accepted_by_id", sa.Integer(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("performed_by_id", sa.Integer(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_by_id"],
            ["employees.id"],
            name=op.f("fk_product_steps_accepted_by_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_id"],
            ["employees.id"],
            name=op.f("fk_product_steps_performed_by_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_steps_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["step_definition_id"],
            ["step_definitions.id"],
            name=op.f("fk_product_steps_step_definition_id_step_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_steps")),
    )
    op.create_index(op.f("ix_product_steps_id"), "product_steps", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_steps_id"), table_name="product_steps")
    op.drop_table("product_steps")
    op.drop_index(op.f("ix_daily_plans_id"), table_name="daily_plans")
    op.drop_table("daily_plans")
    op.drop_index(op.f("ix_step_definitions_id"), table_name="step_definitions")
    op.drop_table("step_definitions")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_access_tokens_created_at"), table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_step_templates_id"), table_name="step_templates")
    op.drop_table("step_templates")
    op.drop_index(op.f("ix_processes_id"), table_name="processes")
    op.drop_table("processes")
    op.drop_index(op.f("ix_backups_id"), table_name="backups")
    op.drop_table("backups")
    # ### end Alembic commands ###
