"""добавлена таблица Inventory

Revision ID: 83124da12c46
Revises: b35abb8b7a11
Create Date: 2026-05-22 14:15:35.131521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "83124da12c46"
down_revision: Union[str, None] = "b35abb8b7a11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventories",
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_inventories_created_by_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
    )
    op.create_index(
        op.f("ix_inventories_id"), "inventories", ["id"], unique=True
    )
    op.create_table(
        "inventory_items",
        sa.Column("inventory_id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("step_definition_id", sa.Integer(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
            name=op.f("fk_inventory_items_inventory_id_inventories"),
        ),
        sa.ForeignKeyConstraint(
            ["step_definition_id"],
            ["step_definitions.id"],
            name=op.f(
                "fk_inventory_items_step_definition_id_step_definitions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
        sa.UniqueConstraint(
            "inventory_id", "serial_number", name="uq_inventory_serial"
        ),
    )
    op.create_index(
        op.f("ix_inventory_items_id"), "inventory_items", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_items_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_inventories_id"), table_name="inventories")
    op.drop_table("inventories")
    # ### end Alembic commands ###
